// Generated by https://quicktype.io

import { Feature } from "../models/MasterPointInterface";

export interface MasterPointPaginationRes {
    docs:          Feature[];
    totalDocs:     number;
    limit:         number;
    totalPages:    number;
    page:          number;
    pagingCounter: number;
    hasPrevPage:   boolean;
    hasNextPage:   boolean;
    prevPage:      null;
    nextPage:      null;
}

export interface MasterPointPaginationReq {
    searchParams: SearchParams;
    sortOrder: "asc" | "desc";
    sortBy: 'length' | 'depth' | 'pdep' | 'elev';
    page: number;
    limit: number;
    pagination:boolean;
}

export interface SearchParams {
    name: string;
    tcsnumber: string;
    lengthL: number | null;
    lengthR: number | null;
    lengthCmp: '<' | '<='; //todo
    pdepL: number | null; //todo
    pdepR: number | null; //todo
    pdepCmp: '<' | '<='; //todo
    depthL: number | null; //todo
    depthR: number | null; //todo
    depthCmp: '<' | '<='; //todo
    elevL: number | null; //todo
    elevR: number | null; //todo
    elevCmp: '<' | '<='; //todo
    psL: number | null; //todo
    psR: number | null; //todo
    psCmp: '<' | '<='; //todo
    co_name: string[];
    ownership: string[];
    topo_name: string;
    topo_indi: string[];
    gear: string[];
    ent_type: string[];
    field_indi: string[];
    map_status: string[];
    geology: string;
    geo_age: string;
    phys_prov: string;
  };



