// Generated by https://quicktype.io

import { Feature } from "../models/MasterPointInterface";

export interface MasterPointPaginationRes {
    docs:          Feature[];
    totalDocs:     number;
    limit:         number;
    totalPages:    number;
    page:          number;
    pagingCounter: number;
    hasPrevPage:   boolean;
    hasNextPage:   boolean;
    prevPage:      null;
    nextPage:      null;
}

export interface MasterPointPaginationReq {
    searchParams: SearchParams;
    sortOrder: "asc" | "desc";
    page: number;
    limit: number;
    pagination:boolean;
}

export interface SearchParams {
    name: string;
    tcsnumber: string;
    lengthL: number | string; //todo
    lengthR: number | string; //todo
    lengthCmp: '<' | '<='; //todo
    pdepL: number | string; //todo
    pdepR: number | string; //todo
    pdepCmp: '<' | '<='; //todo
    depthL: number | string; //todo
    depthR: number | string; //todo
    depthCmp: '<' | '<='; //todo
    elevL: number | string; //todo
    elevR: number | string; //todo
    elevCmp: '<' | '<='; //todo
    psL: number | string; //todo
    psR: number | string; //todo
    psCmp: '<' | '<='; //todo
    co_name: string[];
    ownership: string[];
    topo_name: string; //todo
    topo_indi: string[]; //todo
    gear: string[]; //todo
    ent_type: string[]; //todo
    field_indi: string[]; //todo
    map_status: string[]; //todo
    geology: string; //todo
    geo_age: string; //todo
    phys_prov: string; //todo
  };



