// Generated by https://quicktype.io

import {Feature} from './geoJsonInterface';

export interface MasterPointPaginationRes {
  docs: Feature[];
  totalDocs: number;
  limit: number;
  totalPages: number;
  page: number;
  pagingCounter: number;
  hasPrevPage: boolean;
  hasNextPage: boolean;
  prevPage: null;
  nextPage: null;
}

export interface MasterPointPaginationReq {
  searchParams: SearchParams;
  sortOrder: 'asc' | 'desc';
  sortBy: 'length' | 'depth' | 'pdep' | 'elev' | 'ps' | 'relevance';
  page: number;
  limit: number;
  pagination: boolean;
}

export interface SearchParams {
  name: string;
  tcsnumber: string;
  lengthL: number | null;
  lengthR: number | null;
  lengthCmp: '<' | '<=';
  pdepL: number | null;
  pdepR: number | null;
  pdepCmp: '<' | '<=';
  depthL: number | null;
  depthR: number | null;
  depthCmp: '<' | '<=';
  elevL: number | null;
  elevR: number | null;
  elevCmp: '<' | '<=';
  psL: number | null;
  psR: number | null;
  psCmp: '<' | '<=';
  co_name: string[];
  ownership: string[];
  topo_name: string;
  topo_indi: string[];
  gear: string[];
  ent_type: string[];
  field_indi: string[];
  map_status: string[];
  geology: string;
  geo_age: string;
  phys_prov: string;
  narr: string;
}
