// Generated by https://quicktype.io

import {Feature} from './geoJsonInterface';

export interface MasterPointPaginationRes {
  docs: Feature[];
  totalDocs: number;
  limit: number;
  totalPages: number;
  page: number;
  pagingCounter: number;
  hasPrevPage: boolean;
  hasNextPage: boolean;
  prevPage: null;
  nextPage: null;
}

export interface MasterPointPaginationReq {
  searchParams: SearchParams;
  sortOrder: 'asc' | 'desc';
  sortBy: 'length' | 'depth' | 'pdep' | 'elev';
  page: number;
  limit: number;
  pagination: boolean;
}

export interface SearchParams {
  name: string;
  tcsnumber: string;
  lengthL: number | null; //todo
  lengthR: number | null; //todo
  lengthCmp: '<' | '<='; //todo
  pdepL: number | null; //todo
  pdepR: number | null; //todo
  pdepCmp: '<' | '<='; //todo
  depthL: number | null; //todo
  depthR: number | null; //todo
  depthCmp: '<' | '<='; //todo
  elevL: number | null; //todo
  elevR: number | null; //todo
  elevCmp: '<' | '<='; //todo
  psL: number | null; //todo
  psR: number | null; //todo
  psCmp: '<' | '<='; //todo
  co_name: string[];
  ownership: string[];
  topo_name: string; //todo
  topo_indi: string[]; //todo
  gear: string[]; //todo
  ent_type: string[]; //todo
  field_indi: string[]; //todo
  map_status: string[]; //todo
  geology: string; //todo
  geo_age: string; //todo
  phys_prov: string; //todo
}
