// Generated by https://quicktype.io

export interface ParcelResponseInterface {
    id:              number;
    headline:        string;
    fields:          Fields;
    key:             { [key: string]: string };
    has_premium:     boolean;
    reference_links: ReferenceLinks;
    streetview:      string;
    birdseye:        string;
    gmaps_url:       string;
    spec:            Spec;
    path:            string;
    centroid:        number[];
    geometry:        Geometry;
    blexts:          any[];
    blext_key:       BlextKey;
    bookmarked:      null;
    context:         Context[];
    metadata:        Metadata;
    notices:         BlextKey;
    others:          any[];
    status:          string;
    sources:         any[];
}

export interface BlextKey {
}

export interface Context {
    headline:    string;
    name:        string;
    path:        string;
    category?:   string;
    active?:     boolean;
    verse_path?: string;
}

export interface Fields {
    parcelnumb:              string;
    owner:                   string;
    address:                 string;
    scity:                   string;
    szip:                    string;
    usecode:                 string;
    zoning:                  null;
    yearbuilt:               null;
    landval:                 number;
    parval:                  number;
    saleprice:               number;
    saledate:                string;
    owner2:                  string;
    owner3:                  null;
    mailadd:                 string;
    mail_address2:           null;
    mail_unit:               null;
    mail_city:               string;
    mail_state2:             string;
    mail_zip:                string;
    mailingcountry:          null;
    legaldesc:               string;
    book:                    null;
    page:                    null;
    block:                   null;
    lot:                     string;
    neighborhood:            string;
    subdivision:             null;
    gisacre:                 number;
    parcelid:                string;
    camaacct:                string;
    parent_:                 null;
    map:                     string;
    cntlmap:                 string;
    parcel:                  string;
    deedacres:               number;
    specint:                 string;
    greenbelt:               string;
    cama:                    string;
    um:                      null;
    umvalue:                 null;
    review:                  null;
    parcelcomments:          string;
    improvedstatus:          string;
    totalarea:               string;
    accounttype:             string;
    marketarea:              string;
    appraisalarea:           string;
    streetcondition:         string;
    topography:              string;
    traffic:                 string;
    salelandusecode:         string;
    grantor:                 null;
    grantee:                 string;
    baths:                   number;
    beds:                    null;
    buildingtypedescription: null;
    condocomplex:            null;
    totalyarditemvalue:      number;
    totallandarea:           number;
    totalfinishedarea:       number;
    business:                null;
    businessname:            null;
    propertystatus:          string;
    totalassessedvalue:      number;
    nalcode:                 string;
    soldasvacant:            string;
    ll_gisacre:              number;
    ll_gissqft:              number;
}

export interface Geometry {
    type:        string;
    coordinates: Array<Array<number[]>>;
}

export interface Metadata {
    headline:      string;
    table_updated: string;
    last_refresh:  string;
}

export interface ReferenceLinks {
    lbcs_activity:  string;
    lbcs_function:  string;
    lbcs_ownership: string;
    lbcs_structure: string;
    lbcs_site:      string;
}

export interface Spec {
    dataset: string;
    geoid:   string;
    city:    string;
    id:      number;
}